### ISSUE TITLE
How can I get the  ImageNet-16H Dataset?

### ISSUE THREAD

**Issue by Taoismer** [GavinKerrigan/conf_matrix_and_calibration#1]

**Comment by GavinKerrigan** [comment]
Hi,

The ImageNet-16H dataset can be downloaded on the OSF, [linked here](https://osf.io/2ntrf/?view_only=9ec9cacb806d4a1ea4e2f8acaada8f6c).

Please also see our PNAS paper [[Steyvers et al., 2022]](https://www.pnas.org/doi/10.1073/pnas.2111547119) describing the dataset in more detail.
